# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 365073a639d1420f4c29bd11a834d50e89137889c0bf649684a48150b5b5c1e80e7c945f6be52ced40294e0b5010a21b4573d94727ecfefac955a345c798ba54

test:
  secret_key_base: 57a25c792631bda1d6d63dce9a43c65dbb9eaf633c5f06c0a04a0b2549adf2ce6f84843238a92fec7a6083cf2061b13172c8cb3397e57102a5bfdaadcc6b5544

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
